#ifdef GRPC_INCLUDE_BEGIN

/***
 * this header makes it possible to compile
 * files generated by gRPC with unreal engine
 *
 * THIS HEADER HAS TO BE INCLUDED AFTER THE LAST GENERATED HEADER
 */

#if (defined(PLATFORM_HOLOLENS) | defined(PLATFORM_WINDOWS))
#pragma warning(pop)
THIRD_PARTY_INCLUDES_END
#include "Windows/HideWindowsPlatformAtomics.h"
#endif

#undef GRPC_INCLUDE_BEGIN

#else

#pragma message("Not matching begin header")

#endif
